
version: '3.8'
services:
  # react-app:
  #   image: vite_app
  #   stdin_open: true
  #   ports:
  #     - "5173:5173"
  #   environment:
  #  --------> use polling for file changes
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./vite-react:/app
  #     - /app/node_modules



  #  lets try another approach
  vite-react:
    build: ./vite-react
    container_name: vite_app
    ports:
      - "5173:5173"
    volumes:
      - ./vite-react:/app
      - /app/node_modules
    environment:
    # --------> use polling for file changes
      - CHOKIDAR_USEPOLLING=true  



  express:
    build: ./express
    container_name: express_app
    ports:
      - "5000:5000"
    volumes:
      - ./express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true



  create-react-app:
    build: ./create-react-app
    container_name: create_react_app
    ports:
      - "5173:5173"
    volumes:
      - "./create-react-app:/app:delagated"
      - /app/node_modules
    environment:
    # --------> use polling for file changes
      - CHOKIDAR_USEPOLLING=true 